### PR TITLE
Sherzod 

### PR DESCRIPTION
**Pull request by Sherzod94UZB**

### CODE REVIEW

**Review by daja0923 — CHANGES_REQUESTED** [review]
Make a pure function on Fibonacci, make it a practice.
Test your algorithm for input 0, it should return 0.
This is the Fibonacci numbers: 
fib(0) = 0; 
fib(1) = 1; 
And for inputs 2 and above: fib(n) = fib(n-2) + fib(n-1)

**Comment by Sherzod94UZB** [comment]
Enter the number: 
7
Fibonacci steps upto 7 : 
0 1 1 2 3 5 8

**Review by daja0923 — CHANGES_REQUESTED** [review]
Your recursive function is correct.
Loop one is incorrect. You did not create a function for it.

**Review by daja0923 — CHANGES_REQUESTED** [review]
Create a different Pull Request for Queen attack.

**Pull request closed without merging**
